
export const USERLOADING="USERLOADING";
export const USERSUCCESS="USERSUCCESS";
export const USERFAIL="USERFAIL";


export const REGISTERLOADING="REGISTERUSERLOADING";
export const REGISTERSUCCESS="REGISTERUSERSUCCESS";
export const REGISTERFAIL="REGISTERUSERFAIL";